[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["."]

[tool.mypy]
strict = true
python_version = "3.12"

# Optional: ignore virtual environment and build folders
exclude = [
  '\.venv',
  'build',
  'dist'
]

# Optional: if you want different settings per subpackage
# e.g. automata strict, cli less strict
[[tool.mypy.overrides]]
module = "cli.*"
strict = false
